import type { ElectrobunConfig } from 'electrobun'

import pkg from './package.json' with { type: 'json' }

const config: ElectrobunConfig = {
  app: {
    name: 'Manifesto',
    identifier: 'dev.manifesto.app',
    version: pkg.version,
    description: pkg.description,
  },
  build: {
    mac: { icons: 'assets/app-icon.iconset' },
    linux: { icon: 'assets/app-icon.png' },
    win: { icon: 'assets/app-icon.ico' },
    // Electrobun 2 defaults the main process to Cottontail. This app stays on Bun:
    // `src/bun/windows-dpi.ts` calls user32 through `bun:ffi`, and its failure mode is
    // silent — the try/catch returns an unscaled display and Windows bitmap-stretches
    // the UI. Moving to Cottontail is a separate change with its own DPI check.
    mainProcess: 'bun',
    bun: { entrypoint: 'src/bun/index.ts' },
    views: {
      mainview: {
        entrypoint: 'src/webview/index.tsx',
        // Everything after `entrypoint` is forwarded to the bundler, so these are
        // bundler options.
        //
        // JSX is deliberately absent: Electrobun 2 reads the project's tsconfig, so
        // `jsxImportSource: 'preact'` reaches the view build on its own. v1 needed the
        // pairing spelled out here; `scripts/check-view-bundle.ts` is what would
        // notice if the built view ever resolved against React again.
        //
        // The view is loaded with `<script src>`, not as a module. Say so rather than
        // inheriting a default: as ESM, the bundle's top-level syntax stops parsing
        // and the drop guards die with it.
        format: 'iife',
        // Preact ships dev-only branches behind NODE_ENV; without the define they stay
        // in and the bundle is roughly three times larger.
        define: { 'process.env.NODE_ENV': JSON.stringify('production') },
        minify: true,
      },
    },
    copy: {
      'src/webview/index.html': 'views/mainview/index.html',
      // Generated from logo.svg; PNG avoids WebView2's custom-protocol SVG MIME fallback.
      'assets/app-icon.png': 'views/mainview/app-icon.png',
      // Generated by `bun run css` before the app build. Gitignored.
      '.tailwind/app.css': 'views/mainview/app.css',
      // resvg's WASM ships beside the app code. The Bun process resolves it from
      // `import.meta.dir`, never `process.cwd()` — cwd is `bin/`, not the app root.
      'node_modules/@resvg/resvg-wasm/index_bg.wasm': 'resvg.wasm',
    },
  },
}

export default config
