import type { BunPlugin } from 'bun'
import type { ElectrobunConfig } from 'electrobun/bun'

import pkg from './package.json' with { type: 'json' }

/**
 * Keep two 3D engines out of the main-process bundle.
 *
 * `electrobun/bun` re-exports `three` and `@babylonjs/core` as a convenience for people
 * building 3D apps. Nothing inside Electrobun uses them — they are imported at the top of
 * its barrel and only re-exported — but both packages have side effects, so the bundler
 * cannot drop them, and importing `BrowserWindow` costs **9.7 MB** of WebXR and WebGPU
 * shader code this app will never call.
 *
 * Resolving them to an empty module is safe precisely because the only thing that ever
 * touches them is the re-export: `Electrobun.three` becomes an empty namespace, and
 * nothing here reads it. If a future version of Electrobun starts using them internally,
 * this breaks loudly at startup rather than quietly — which is the right failure.
 *
 * `external` would not work: the imports are evaluated at load time and the packages are
 * not shipped with the app, so it would fail on launch instead of at build.
 */
const dropUnusedEngines: BunPlugin = {
  name: 'manifesto-drop-3d-engines',
  setup(build) {
    build.onResolve({ filter: /^(?:three|@babylonjs\/core)$/u }, () => ({
      path: 'manifesto-unused-engine',
      namespace: 'manifesto-stub',
    }))
    build.onLoad({ filter: /.*/u, namespace: 'manifesto-stub' }, () => ({
      contents: 'export default {}',
      loader: 'js',
    }))
  },
}

const config: ElectrobunConfig = {
  app: {
    name: 'Manifesto',
    identifier: 'dev.manifesto.app',
    version: pkg.version,
    description: pkg.description,
  },
  build: {
    mac: { icons: 'assets/app-icon.iconset' },
    linux: { icon: 'assets/app-icon.png' },
    win: { icon: 'assets/app-icon.ico' },
    bun: { entrypoint: 'src/bun/index.ts', plugins: [dropUnusedEngines] },
    views: {
      mainview: {
        entrypoint: 'src/webview/index.tsx',
        // Everything after `entrypoint` is spread straight into `Bun.build`, so these
        // are Bun bundler options.
        //
        // `jsx` must be set here, not left to tsconfig: Electrobun invokes Bun.build
        // from its own root, so the project's `jsxImportSource` is not picked up and
        // JSX resolves against `react/jsx-runtime`, which is not installed.
        jsx: { runtime: 'automatic', importSource: 'preact' },
        // Preact ships dev-only branches behind NODE_ENV; without the define they stay
        // in and the bundle is roughly three times larger.
        define: { 'process.env.NODE_ENV': JSON.stringify('production') },
        minify: true,
      },
    },
    copy: {
      'src/webview/index.html': 'views/mainview/index.html',
      // Generated from logo.svg; PNG avoids WebView2's custom-protocol SVG MIME fallback.
      'assets/app-icon.png': 'views/mainview/app-icon.png',
      // Generated by `bun run css` before the app build. Gitignored.
      '.tailwind/app.css': 'views/mainview/app.css',
      // resvg's WASM ships beside the app code. The Bun process resolves it from
      // `import.meta.dir`, never `process.cwd()` — cwd is `bin/`, not the app root.
      'node_modules/@resvg/resvg-wasm/index_bg.wasm': 'resvg.wasm',
    },
  },
}

export default config
